"""Generate pipeline_notes.json (+ pipeline_notes.js for the file:// viewer) from the `plain` notes
that live ON the decision units in the code.

This is the SINGLE SOURCE for the human/LLM "what this stage does + how it fails" notes: each note lives
as a `plain` attribute on its classifier / assembler / pass (or a fork `_PLAIN` constant at the record
site), and is ALSO carried into assessment.json (node_help) → the LLM failure prompt. Edit a unit's
`plain`, re-run this, commit. The no-drift test in unit/test_pipeline_map.py fails if the committed
pipeline_notes.json falls out of sync, so the visual tree + the LLM report can never disagree with code.

Run:  python3 tests/conversion/gen_pipeline_notes.py     # rewrites pipeline_notes.json + pipeline_notes.js
"""
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.abspath(os.path.join(_HERE, '..', '..'))
sys.path.insert(0, os.path.join(_REPO, 'app', 'Python'))

import mistral_ocr as M                       # noqa: E402
import digestion.strategySelection.strategy as S               # noqa: E402
import digestion.bibliographyExtraction.bibliography as B           # noqa: E402
import digestion.citationLinking.citation_link_rules as C    # noqa: E402
import process_document as P                  # noqa: E402
import epub_normalizer as E                   # noqa: E402
import simple_md_to_html as MD                # noqa: E402


def collect_notes():
    """Walk the registries / fork constants and return {node_key: plain}. The node_key namespaces
    (classifier:/assembler:/recovery:/epub:) match the lookup map in pipeline_map.html."""
    notes = {}
    # PDF footnote-layout classifiers (the G1–G5 ladder + the unknown fall-through).
    for c in M.PDF_CLASSIFIERS + [M.UnknownClassifier()]:
        notes['classifier:' + c.name] = c.plain
    # PDF assemblers (per layout) + the default/unknown assembler.
    for name, a in M.PDF_ASSEMBLERS.items():
        notes['assembler:' + name] = a.plain
    notes['assembler:default'] = M.DefaultAssembler.plain
    # The three footnote-recovery layers + the harvest-fidelity scorer.
    notes['recovery:markers'] = M.convert_inline_footnote_markers.plain
    notes['recovery:mojibake'] = M.scan_footnote_mojibake.plain
    notes['recovery:missingdefs'] = M.recover_missing_defs.plain
    notes['fidelity'] = M.assess_harvest_fidelity.plain
    # Backend fork nodes (recorded in their conversion modules).
    notes['strategy'] = S._STRATEGY_PLAIN
    notes['guard'] = S._GUARD_PLAIN
    notes['bibliography'] = B._BIBLIOGRAPHY_PLAIN
    notes['citation'] = C._CITATION_PLAIN
    notes['audit'] = P.AuditPass.plain
    # EPUB frontend nodes.
    notes['epub:detection'] = E.EpubNormalizer._DETECTION_PLAIN
    notes['epub:linking'] = E.EpubNormalizer._LINKING_PLAIN
    notes['epub:overview'] = E.EpubNormalizer._OVERVIEW_PLAIN
    notes['epub:load'] = E.EpubNormalizer._LOAD_PLAIN
    notes['epub:structural'] = E.EpubNormalizer._STRUCTURAL_PLAIN
    # Markdown ingestion (also the back half of the PDF path).
    notes['md:convert'] = MD.convert_markdown_to_html.plain
    notes['epub:headings'] = E.EpubNormalizer._HEADINGS_PLAIN
    notes['epub:bibdetect'] = E.EpubNormalizer._BIBDETECT_PLAIN
    notes['epub:finalnorm'] = E.EpubNormalizer._FINALNORM_PLAIN
    # one note per EPUB footnote-detection scheme (the run-all fan in TRANSFORM_PIPELINE).
    for name in E.EpubNormalizer._DETECTOR_NEEDS:
        notes['epub:detector:' + name] = getattr(E, name).plain
    # one note per EPUB heading-detection scheme (Phase 1, before footnotes).
    for name in E.EpubNormalizer._HEADING_NEEDS:
        notes['epub:heading:' + name] = getattr(E, name).plain
    return notes


def render_json(notes):
    return json.dumps(notes, ensure_ascii=False, indent=2, sort_keys=True) + '\n'


def main():
    notes = collect_notes()
    missing = [k for k, v in notes.items() if not (v and v.strip())]
    if missing:
        raise SystemExit('decision units missing a `plain` note: ' + ', '.join(sorted(missing)))
    body = render_json(notes)
    with open(os.path.join(_HERE, 'pipeline_notes.json'), 'w', encoding='utf-8') as f:
        f.write(body)
    # JS form for the file:// HTML viewer — fetch() is blocked under file://, but <script src> is not.
    with open(os.path.join(_HERE, 'pipeline_notes.js'), 'w', encoding='utf-8') as f:
        f.write('// GENERATED by gen_pipeline_notes.py from the code\'s `plain` notes — do not hand-edit.\n')
        f.write('window.PIPELINE_NOTES = ' + body.rstrip('\n') + ';\n')
    print('wrote %d notes -> pipeline_notes.json + pipeline_notes.js' % len(notes))
    return notes


if __name__ == '__main__':
    main()
