// HAND-AUTHORED overlay for pipeline_map.html — the deep per-node prose that ISN'T in the code:
// readable gate thresholds, curated evidence lists, the "considered / writes" paragraphs, assembler
// step-details, recovery safety notes. Keyed by the diagram node-id (from gen_pipeline_map.py).
// Everything else (the diagram, node names, code_refs, would_need, questions, the 💡 notes) is
// GENERATED — see pipeline_map_data.js + pipeline_notes.js. A node with no entry here just shows its
// generated name + note, so adding a classifier never breaks the viewer; write its prose here when ready.
window.PIPELINE_MAP_OVERLAY = {
  // ---- PDF classifier gates (the thresholds live in each PdfClassifier.matches(); summarised here) --
  'C_none': { gate: 'pages_with_refs == 0', rejected: '"N page(s) carry in-text references" (when refs do exist)', confidence: '1.0 — unambiguous' },
  'C_wackSTEMbibliographyNotes': { gate: 'ref-spread ≥3 AND co-loc <0.2 AND notes==0 AND resets ≤3 AND (reset-freq <0.2 OR max-ref >50)', rejected: '"ref-number page-spread S (need ≥3) and co-location C (need <0.2)"', confidence: '+0.3 spread≥5 · +0.3 numbers-on-multiple-pages>10 · +0.2 co<0.1 · +0.2 no Notes' },
  'C_page_bottom': { gate: '(co-loc >0.4 AND pages-with-both ≥3 AND reset-freq <0.1 AND max-ref >10)  OR  (co-loc >0.5 AND reset-freq >0.4)', rejected: '"co-location C / reset-freq R fit neither page_bottom rule (continuous / restart)"', confidence: '+0.3 co>0.8 (or +0.15 co>0.4) · +0.3 resets>0.7 (or +0.25 continuous & high max-ref) · +0.2 no Notes · +0.2 consistent page-numbers' },
  'C_chapter_endnotes': { gate: '(notes>0 AND co-loc <0.3)  OR  (co-loc <0.3 AND defs>0 AND reset-freq >0.3)  OR  (co-loc <0.15 AND defs>5 AND resets ≥3)', rejected: '"no Notes-header page and co-location C/reset-freq R miss the endnote rules"', confidence: '+0.3 Notes>0 · +0.3 co<0.1 · +0.2 resets>0 · +0.2 def-clustering<0.2' },
  'C_document_endnotes': { gate: 'co-loc <0.15 AND def-clustering <0.1', rejected: '"co-location C (need <0.15) and def-clustering D (need <0.1)"', confidence: '+0.3 co<0.05 · +0.3 def-clustering<0.05 · +0.2 no Notes · +0.2 no resets', note: 'if even this misses → unknown ✗ (fall-through, confidence 0.0 — a prime review candidate)' },

  // ---- assembler step-details (what each builds) -------------------------------------------------
  'A_default': { detail: 'post_combine: normalize_all_footnote_refs + normalize_footnote_defs + format [^N]: + rejoin_page_breaks. Serves "none" (no footnotes) AND "unknown" (nothing matched).' },
  'A_wackSTEMbibliographyNotes': { detail: 'post_combine: wrap_stem_citations + wrap_stem_definitions (the backend STEM pass turns these into links).' },
  'A_page_bottom': { detail: 'per_page: renumber_page_footnotes + split body from definitions · post_combine: rejoin body + append the collected, reformatted definitions.' },
  'A_chapter_endnotes': { detail: 'setup: precompute per-chapter offsets + notes-section transitions · per_page: convert refs + apply offset · post_combine: fix def formatting + rejoin.' },
  'A_document_endnotes': { detail: 'per_page: convert bracket/superscript refs → [^N] · post_combine: format [^N]: + rejoin.' },

  // ---- recovery layer detail --------------------------------------------------------------------
  'REC1': { needs_pdf: false, does: 'Convert superscript / $^5$ / [N] / bare ".46 " → [^N].', safety: 'SEQUENTIAL VALIDATION — a candidate is only converted if its number fits between the surrounding KNOWN [^N] refs, so years ("2015"), table numbers and prices are not mistaken for footnotes.', needs: 'No PDF — works on the OCR text alone (so it ALWAYS runs, even in the replay harness).', test: 'test_footnote_recovery.py · test_mistral_ocr.py' },
  'REC2': { needs_pdf: true, does: 'Detect low printable-ratio def pages → re-extract them via pypdf → splice clean defs back in. Emits footnote_warnings (recovered / unrecovered).', safety: 'Only fires on pages that are actually mojibake (compute_printable_ratio below threshold).', needs: 'NEEDS the real PDF — runs in the live import but NOT in the cached-OCR replay.', test: 'test_pdf_recovery_real.py (opt-in: RUN_PYPDF_RECOVERY=1)' },
  'REC3': { needs_pdf: true, does: 'For each ref with no def: find that number in the pypdf-extracted defs and emit it. Range-filters, de-dupes, applies multi-paper offsets, can overwrite a corrupt OCR def.', safety: 'pypdf "defs" whose text is itself mojibake are REJECTED (recorded as unrecovered). The matcher is pure logic.', needs: 'The extraction NEEDS the PDF; the matcher is unit-tested without one.', test: 'test_footnote_recovery.py (matcher) · test_pdf_recovery_real.py (end-to-end)' },

  // ---- backend fork detail (evidence keys + considered/writes prose) -----------------------------
  'SIG': { evidence: ['co_location_ratio', 'reset_frequency', 'def_clustering_ratio', 'ref_number_max_page_spread', 'notes_page_count', 'max_ref_number', 'page_summary (per-page refs/defs)'], considered: 'each OTHER layout → its rejected_because + would_need (ONE fork; expand the ladder + click a gate to see each). The chosen layout contributes the decision + margin.', confidence: 'per-class score (page_bottom rewards high co-location + a high max-ref); unknown = 0.0 fall-through', writes: 'written FIRST by write_classification_assessment → assessment.json; process_document seeds from it so the trace spans both stages' },
  'STRAT': { evidence: ['position_ratio', 'ref_position_ratio', 'has_footnote_resets', 'has_distributed_hrs', 'has_structured_sections', 'has_section_pattern', 'duplicate_numbers'], considered: '_strategy_considered: each other strategy → rejected_because + would_need', confidence: 'per-rule (0.85 resets+HRs … 0.3 default fall-through); a FALL-THROUGH margin marks a shaky default', writes: 'ASSESSMENT.record(module=strategy_selection) → assessment.json' },
  'BIB': { evidence: ['entries', 'map_keys', 'collisions_suffixed', 'duplicates_merged', 'dropped_no_keys', 'detection (heading|reverse_scan)'], considered: 'when author+year collide, a bare "(Author Year)" can\'t disambiguate → resolves to the LAST entry', confidence: '1 − dropped/(entries+dropped); margin names dropped (unkeyable = unlinkable) + collisions', writes: 'ASSESSMENT.record(module=bibliography_extraction) — the link TARGETS the citation linker matches against' },
  'GUARD': { evidence: ['definition_range / count', 'missing_in_sequence (gaps)', 'orphan_markers (refs with no def)'], considered: 'link vs suppress, with the guard that fired', confidence: '0.8–0.9; the modus operandi: a missing link is honest, a confident WRONG link is not', writes: 'ASSESSMENT.record(module=footnote_linking_guard) — both outcomes recorded with evidence' },
  'LINK': { evidence: ['found', 'linked', 'unlinked', 'bibliography_entries', 'likely_not_citations', 'unlinked_sample (keys tried)'], considered: 'the unmatched citations + the keys generated for them', confidence: 'linked/found — BUT a 0/N against a near-empty bibliography is recorded HIGH (those aren\'t real citations)', writes: 'ASSESSMENT.record(module=citation_linking)' },
  'AUDIT': { evidence: ['total_refs', 'total_defs', 'gaps', 'unmatched_refs', 'unmatched_defs', 'duplicates', '+ samples'], considered: 'the unmatched refs/defs by id (falsifiable — names WHICH ones)', confidence: '1 − faults/total; the vibe gate credits a DROP in these faults, not just more links', writes: 'ASSESSMENT.record(module=footnote_audit) — the second half of the diagnostic loop' },
  'FID': { evidence: ['classification', 'refs_in_ocr', 'defs_in_ocr', 'defs_harvested', 'coverage_vs_refs', 'collision_count', 'pypdf_recovery_attempted', 'pypdf_recovered', 'pypdf_unrecovered'], considered: '"Demand" is anchored on the in-text MARKERS (refs), not raw def-lines. harvest_gap = OCR had the defs, we dropped them; fidelity_loss = OCR itself lost them (CONFIRMED only once pypdf re-extraction also failed); assembly_collisions = emitted but numbers not unique.', confidence: 'ONLY harvest_gap (0.4) + assembly_collisions (0.45) raise the <0.5 flag the vibe loop routes on; fidelity_loss (0.55) + clean/not_applicable/no_footnotes (0.9) stay silent', writes: 'appended by write_classification_assessment as the seq-1 record → assessment.json (live import only — replay is pdf_path=None)' },
};
window.PIPELINE_MAP_OVERLAY['OCRC'] = window.PIPELINE_MAP_OVERLAY['SIG'];   // collapsed PDF node = the classify fork
