<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Stop archiving history for the generated ranking books.
 *
 * `most-recent`, `most-connected`, `most-lit` and `stats` are regenerated by
 * UpdateHomepageJob every fifteen minutes. Each regeneration rewrites their
 * nodes, and the temporal versioning trigger dutifully archives every previous
 * row — roughly 96 full rewrites a day, forever, for books whose "edit history"
 * is meaningless: nobody time-machines a leaderboard. On production this made
 * them the three largest books in a 12 GB nodes_history.
 *
 * A trigger's WHEN clause may only reference OLD or NEW for the events where
 * that alias exists, so the single INSERT/UPDATE/DELETE trigger is split in
 * two: NEW for insert/update, OLD for delete. Both still call versioning() with
 * the same arguments, so behaviour for every OTHER book is unchanged — the
 * Time Machine keeps working exactly as before.
 *
 * Existing rows are NOT touched here: purging is a separate, explicit decision
 * (`php artisan nodes:purge-system-history`).
 */
return new class extends Migration
{
    /** Generated books with no meaningful edit history. Matches the exclusion list already used by SearchService and the canonicalize commands. */
    private const SYSTEM_BOOKS = "'stats', 'most-recent', 'most-connected', 'most-lit'";

    public function up(): void
    {
        $db = DB::connection('pgsql_admin');

        $db->statement('DROP TRIGGER IF EXISTS nodes_versioning_trigger ON nodes');

        $db->statement('
            CREATE TRIGGER nodes_versioning_trigger
            BEFORE INSERT OR UPDATE ON nodes
            FOR EACH ROW
            WHEN (NEW.book NOT IN (' . self::SYSTEM_BOOKS . '))
            EXECUTE FUNCTION versioning(\'sys_period\', \'nodes_history\', \'true\')
        ');

        $db->statement('
            CREATE TRIGGER nodes_versioning_delete_trigger
            BEFORE DELETE ON nodes
            FOR EACH ROW
            WHEN (OLD.book NOT IN (' . self::SYSTEM_BOOKS . '))
            EXECUTE FUNCTION versioning(\'sys_period\', \'nodes_history\', \'true\')
        ');
    }

    public function down(): void
    {
        $db = DB::connection('pgsql_admin');

        $db->statement('DROP TRIGGER IF EXISTS nodes_versioning_trigger ON nodes');
        $db->statement('DROP TRIGGER IF EXISTS nodes_versioning_delete_trigger ON nodes');

        $db->statement("
            CREATE TRIGGER nodes_versioning_trigger
            BEFORE INSERT OR UPDATE OR DELETE ON nodes
            FOR EACH ROW EXECUTE FUNCTION versioning('sys_period', 'nodes_history', 'true')
        ");
    }
};
